"""v3.3.0 — "godfather curriculum" lessons: lossless parse (L3), ground-truth
physical auditor (L2), closed loop (L5), column-level canonical reconcile (L4),
and the SelfAuditor I6 ground-truth invariant (L6).

These tests exercise the two cleanly-isolatable new units end-to-end:

  * _v330_recover_dropped_priorities (L3): every PRIORITY marker in the source
    must survive parsing. Strict _V251_PRIORITY_LINE_RE drops markers with
    spaced/multi-word targets, alt separators, or missing bold. This recovers
    them as best-effort VREQ dicts so a user directive is NEVER lost.

  * SelfAuditor._i6_ground_truth (L6): turns the physical-catalog scorecard
    (produced by the L2 auditor) into a CRITICAL/HIGH/OK/WARN finding so the
    real (physical) adherence gap drives the next cycle even when the in-memory
    verifier reported green.

L2/L4/L5 are physical-catalog paths (need Spark + information_schema), so they
are covered here by static-contract assertions on the deployed source; their
behavior is proven by the live verification run.
"""
import json
import os
import re
import textwrap
import logging

import pytest

NB = os.path.join(os.path.dirname(__file__), "..", "..", "agent", "dbx_vibe_modelling_agent.ipynb")


def _load_src():
    nb = json.load(open(NB))
    return "".join("".join(c.get("source", [])) for c in nb["cells"] if c.get("cell_type") == "code")


def _slice(src, start, end):
    i = src.index(start)
    j = src.index(end, i + len(start))
    return src[i:j]


def _build_l3():
    """Extract the module-level _v330_recover_dropped_priorities verbatim."""
    src = _load_src()
    fn = _slice(src, "def _v330_recover_dropped_priorities(vibe_text, parsed):",
                "\ndef _v251_priority_to_vreq")
    ns = {"re": re}
    exec(fn, ns, ns)
    return ns["_v330_recover_dropped_priorities"]


def _build_i6():
    """Extract _i6_ground_truth and run it inside a minimal collector class."""
    src = _load_src()
    method = _slice(src, "    def _i6_ground_truth(self, scorecard):",
                    "    def _i1_vibe_capture")
    method = textwrap.dedent(method)
    cls = (
        "class _A:\n"
        "  def __init__(s):\n"
        "    s.findings=[]\n"
        "  def _emit(s, alias, inv, sev, summary, evidence=None):\n"
        "    s.findings.append({'alias':alias,'invariant':inv,'severity':sev,'summary':summary,'evidence':evidence or {}})\n"
    )
    cls += textwrap.indent(method, "  ")
    ns = {}
    exec(cls, ns, ns)
    return ns["_A"]()


# ---------------- static contracts ----------------

def test_version_is_330():
    m = re.search(r'__AGENT_VERSION__ = "(\d+)\.(\d+)\.(\d+)"', _load_src())
    assert m is not None
    assert tuple(int(x) for x in m.groups()) >= (3, 3, 0)


def test_curriculum_aliases_present():
    src = _load_src()
    for alias in (
        "priority-lossless-recover",        # L3
        "ground-truth-audit",               # L2
        "ground-truth-audit-requeue",       # L5
        "canonical-reconcile",              # L4
        "canonical-reconcile-requeue",      # L4
        "audit-i6-ground-truth",            # L6
    ):
        assert alias in src, f"missing alias {alias}"


def test_i6_wired_into_audit_and_invariant_list():
    src = _load_src()
    assert '"audit-i6-ground-truth",' in src                 # in INVARIANT_ALIASES tuple
    assert "self._i6_ground_truth(ground_truth_scorecard)" in src
    assert 'ground_truth_scorecard=widgets_values.get("_ground_truth_scorecard")' in src


def test_l2_reuses_live_verifier_not_a_parallel_one():
    # Anti-DRY proof: the physical audit calls the SAME orchestrator verifier.
    assert "orch._verify_deterministic(req, domains_data, products_data, phys_attrs)" in _load_src()


# ---------------- L3 behavioral ----------------

def test_l3_recovers_marker_dropped_by_strict_parser():
    """A PRIORITY line with a spaced multi-word target + en-dash that the strict
    parser missed (absent from `parsed`) must be recovered."""
    recover = _build_l3()
    vibe = (
        "**PRIORITY 1 - rename_attribute: hr.job.code** - clean prefix\n"
        "PRIORITY 2 — add descriptive label to the generic FK column on project asset impact\n"
    )
    parsed = [{"priority_id": 1}]  # strict parser only caught #1
    rec = recover(vibe, parsed)
    pids = {r["priority_id"] for r in rec}
    assert 2 in pids, rec
    assert 1 not in pids, "must not duplicate an already-parsed priority"


def test_l3_does_not_duplicate_already_parsed():
    recover = _build_l3()
    vibe = "**PRIORITY 5 - remove_fk: a.b.c** - reason\n"
    parsed = [{"priority_id": 5}]
    assert recover(vibe, parsed) == []


def test_l3_flags_autogenerated_section_as_non_user():
    recover = _build_l3()
    vibe = (
        "PRIORITY 1 — keep customer domain\n"
        "=== AUTO-GENERATED NEXT_VIBES ===\n"
        "PRIORITY 9 — internal self-audit follow-up\n"
    )
    rec = {r["priority_id"]: r for r in recover(vibe, [])}
    assert rec[1]["is_user_directive"] is True
    assert rec[9]["is_user_directive"] is False


def test_l3_every_recovered_marker_has_vreq_id_and_target_or_reason():
    recover = _build_l3()
    vibe = "PRIORITY 3 — ensure every table carries a source_table tag\n"
    rec = recover(vibe, [])
    assert len(rec) == 1
    r = rec[0]
    assert r["vreq_id"] == "P003"
    assert (r["target"] or r["reason"]), "recovered VREQ must carry target or reason"


# ---------------- L6 behavioral ----------------

def test_i6_low_physical_adherence_is_critical():
    a = _build_i6()
    a._i6_ground_truth({"scored": 46, "fulfilled": 20, "failed": 24, "partial": 2, "pct": 43.5})
    f = a.findings[-1]
    assert f["invariant"] == "I6"
    assert f["severity"] == "CRITICAL", f


def test_i6_borderline_is_high_not_ok():
    a = _build_i6()
    a._i6_ground_truth({"scored": 100, "fulfilled": 85, "failed": 15, "partial": 0, "pct": 85.0})
    assert a.findings[-1]["severity"] == "HIGH", a.findings[-1]


def test_i6_meets_target_is_ok():
    a = _build_i6()
    a._i6_ground_truth({"scored": 100, "fulfilled": 95, "failed": 5, "partial": 0, "pct": 95.0})
    assert a.findings[-1]["severity"] == "OK", a.findings[-1]


def test_i6_no_scorecard_is_warn_not_silent():
    a = _build_i6()
    a._i6_ground_truth(None)
    assert a.findings[-1]["severity"] == "WARN", a.findings[-1]
    a2 = _build_i6()
    a2._i6_ground_truth({})  # ran but 0 physical columns -> scored falsey
    assert a2.findings[-1]["severity"] == "WARN", a2.findings[-1]
